### DISCUSSION TITLE
Merge `.spin-inventory.ini` into `.spin.yml`

### DISCUSSION THREAD

**Discussion by jaydrogers** [serversideup/spin#124] [Ideas]
# 👉 Describe the problem
[comment]: <> (What are you trying to solve?)
- It's confusing for new users to manage an inventory file and a `.spin.yml` file

# 👥 Problem evidence & reach
[comment]: <> (How many people have this problem?)
- I spoke with @ijpatricio on this, and he had fantastic feebdack

# 🥰 Describe the "impact" on users?
[comment]: <> (How will this make people's lives better once it is solved?)
- Merging things into a single file will dramatically reduce confusion and allow Spin to be managed on a single source of truth

# 🏆 How to solve this problem
[comment]: <> (Describe the feature that you are proposing and how it will solve the problem)

### Merge inventory into `.spin.yml`
- [ ] Convert the existing [`.spin-inventory.ini`](https://github.com/serversideup/ansible-collection-spin/blob/main/.spin-inventory.example.ini) to a YML structure
- [ ] Merge this into `.spin.yml` under an `inventory` key

### Example Inventory File
```yml
##############################################################
# 👇 Users - You must set at least one user
##############################################################

users:
#   - username: alice
#     name: Alice Smith
#     groups: ['sudo']
#     authorized_keys:
#       - public_key: "ssh-ed25519 AAAAC3NzaC1lmyfakeublickeyMVIzwQXBzxxD9b8Erd1FKVvu alice"

#   - username: bob
#     name: Bob Smith
#     state: present
#     password: "$6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1"
#     groups: ['sudo']
#     shell: "/bin/bash"
#     authorized_keys:
#       - public_key: "ssh-ed25519 AAAAC3NzaC1anotherfakekeyIMVIzwQXBzxxD9b8Erd1FKVvu bob"

##############################################################
# 👇 Providers - You must set at least one provider
##############################################################

providers:
  # - name: digitalocean
  #   token: $DO_API_TOKEN

  # - name: cloudflare
  #   token: $CF_API_TOKEN

  # - name: hetzner
  #   token: $HETZNER_API_TOKEN
  #   backups: true

  # - name: vultr
  #   token: $VULTR_API_TOKEN

##############################################################
# 👇 Inventory - You must set at least one server
##############################################################

inventory:
  - server: server01.example.com
    environment: production
    hardware_profile: 2g-2vcpu-hetzner-ubuntu

##############################################################
# 👇 Deploy User - If you're using GitHub Actions, create a dedicated deploy key
##############################################################

### Learn how to create a secure DEPLOY key and enter the public value below
## https://serversideup.net/open-source/spin/docs/advanced/generating-a-secure-ssh-key#generating-a-deployment-key

# docker_user:
#   username: deploy
#   authorized_ssh_keys: 
#     - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNJGtd7a4DBHsQi7HGrC5xz0eAEFHZ3Ogh3FEFI2345 fake@key"
#     - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFRfXxUZ8q9vHRcQZ6tLb0KwGHu8xjQHfYopZKLmnopQ anotherfake@key"

##############################################################
# 🤓 Advanced Server Configuration
##############################################################

server_timezone: "Etc/UTC"
server_contact: changeme@example.com

# If you the SSH port below, you may need to run `spin provision -p <your-default-ssh-port>`
# to get a connection on your first provision. Otherwise, SSH will try connecting 
# to your new port before the SSH server configuration is updated.
ssh_port: "22"

## You can set this to false to require a password for sudo.
## If you disable passwordless sudo, you must set a password for all sudo users.
## generate an encrypted hash with `spin mkpasswd`. Learn more:
## https://serversideup.net/open-source/spin/docs/command-reference/mkpasswd
use_passwordless_sudo: true

## Email Notifications
postfix_hostname: "{{ inventory_hostname }}"

## Set variables below to enable external SMTP relay
# postfix_relayhost: "smtp.example.com"
# postfix_relayhost_port: "587"
# postfix_relayhost_username: "myusername"
# postfix_relayhost_password: "mysupersecretpassword"

##############################################################
# 🤖 Hardware Profiles
##############################################################

hardware_profile:
  - name: 2g-2vcpu-hetzner-ubuntu
    provider: hetzner
    provider_config:
      server_type: cx11
      image: ubuntu22.04
      location: nbg1
```

# 💯 How do we validate the problem is solved?
[comment]: <> (Explain use cases on how we can measure the success of this implementation)
- [ ] A user can easily set their configurations in one yml file
- [ ] A user can create two servers in two environments (one for staging and one for production)
- [ ] `spin deploy` still works
