### DISCUSSION TITLE
How to restart dev spin up after adding commands?

### DISCUSSION THREAD

**Discussion by akulmehta** [serversideup/spin#148] [Q&A] [answered]
I am very new to docker and spin. In my `docker-compose.dev.yml` file  I have added the commands in the `php` service 

```yml
services:
  php:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
    volumes:
      - .:/var/www/html/
    networks:
      - development
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=HostRegexp(`localhost`)"
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.services.laravel.loadbalancer.server.port=8080"
      - "traefik.http.services.laravel.loadbalancer.server.scheme=http"
    command: | 
      /bin/sh -c "
      php artisan storage:link && 
      php artisan queue:work --tries=3"

```

How can I stop and restart spin so that the commands of storage:link and queue:work are run in the container?
